-- Custom user-defined labels for 2000-sample prediction cycles.
-- cycle_id is the UUID generated by the server per accumulation window.

create table if not exists public.cycle_labels (
  cycle_id  text not null,
  user_id   uuid not null references auth.users(id) on delete cascade,
  label     text not null,
  created_at timestamptz not null default now(),
  primary key (cycle_id, user_id)
);

alter table public.cycle_labels enable row level security;

drop policy if exists "cycle_labels_select_own" on public.cycle_labels;
create policy "cycle_labels_select_own"
  on public.cycle_labels for select
  using (auth.uid() = user_id);

drop policy if exists "cycle_labels_insert_own" on public.cycle_labels;
create policy "cycle_labels_insert_own"
  on public.cycle_labels for insert
  with check (auth.uid() = user_id);

drop policy if exists "cycle_labels_update_own" on public.cycle_labels;
create policy "cycle_labels_update_own"
  on public.cycle_labels for update
  using (auth.uid() = user_id);

drop policy if exists "cycle_labels_delete_own" on public.cycle_labels;
create policy "cycle_labels_delete_own"
  on public.cycle_labels for delete
  using (auth.uid() = user_id);
